version: '3.8'

services:
  api-gateway:
    build: 
      context: ./backend/api_gateway
    ports:
      - "8000:5000"
    environment:
      - MODEL_SERVICE_URL=http://model-service:5001
      - IMAGE_PROCESSING_SERVICE_URL=http://image-processing-service:5002
      - USER_SERVICE_URL=http://user-service:5003
    volumes:
      - shared-data:/app/uploads
      - shared-results:/app/results
    depends_on:
      - model-service
      - image-processing-service
      - user-service
    networks:
      - met-network

  model-service:
    build:
      context: ./backend/model_service
    volumes:
      - ./Data/saved_models:/app/models
      - shared-results:/app/results
      - shared-data:/app/uploads
    networks:
      - met-network
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '4'
        reservations:
          memory: 3G
    restart: unless-stopped
    environment:
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - OPENBLAS_NUM_THREADS=4
      - VECLIB_MAXIMUM_THREADS=4
      - NUMEXPR_NUM_THREADS=4

  image-processing-service:
    build:
      context: ./backend/image_processing_service
    volumes:
      - shared-results:/app/results
    networks:
      - met-network
    depends_on:
      - model-service
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=met_user_service
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - met-network
    command: --default-authentication-plugin=mysql_native_password
      
  user-service:
    build:
      context: ./backend/user_service
    environment:
      - JWT_SECRET_KEY=change-this-in-production
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=met_user_service
    depends_on:
      - mysql
    networks:
      - met-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - met-network

networks:
  met-network:
    driver: bridge

volumes:
  shared-data:
  shared-results:
  mysql-data:
