version: '3'

services:
  image-processing-service:
    build: 
      context: ./backend/image_processing_service
      dockerfile: Dockerfile
    volumes:
      - ./backend/image_processing_service:/app
    restart: always
