# Model Registry Configuration
# Lists all available models and their metadata
# The active_model field indicates which model is currently in use

active_model: 'brats_t1ce_v1'

models:
  brats_t1ce_v1:
    model_path: '/app/models/brats_t1ce.pth'
    description: 'UNETR model trained on BraTS T1CE images'
    metadata:
      training_date: '2023-05-15'
      input_dim: 1
      output_dim: 4
      architecture: 'UNETR'
      notes: 'Initial production model'

# Add new models here as they are trained
# Example:
#  brats_t1ce_v2:
#    model_path: '/app/models/brats_t1ce_v2.pth'
#    description: 'UNETR model with improved performance'
#    metadata:
#      training_date: '2023-08-01'
#      input_dim: 1
#      output_dim: 4
#      architecture: 'UNETR'
#      notes: 'Retrained with more data'
